### PR TITLE
fixed file type in description of read_json()

### PR DESCRIPTION
**Pull request by notestaff**
### Checklist
- [X] Pull request details were added to CHANGELOG.md

### CODE REVIEW

**Comment by geoffjentry** [comment]
I'm curious what other folks think here. Traditionally we've taken the stance to not retroactively fix issues like this - i.e. official versions of the spec aren't living documents.That does of course bring some cons to the party along with the pros it has

**Comment by notestaff** [comment]
Could also make a separate "errata" document, and add to the original only footnotes with a hyperlink to the erratum.

But it seems that the "official version of the spec" never really specified that read_json() argument should be a TSV file, it just left implementers to figure out that there's a typo.

**Comment by jdidion** [comment]
I like the idea of an errata document.

**Comment by geoffjentry** [comment]
@jdidion likewise

**Comment by notestaff** [comment]
If an errata document, should an unofficial version with the errata applied (and highlighted?) be maintained as well?  Should the original be annotated with links/footnotes to errata?

**Comment by aofarrel** [comment]
Any updates on this? There are a few others with the WDL 1.0 spec which need to be addressed, but if neither an errata nor updates to the spec go through, then unfortunately there is no good resource for anyone wishing to write WDLs compatible with Cromwell/Terra. I get that the spec isn't officially tied to any one executor, but my understanding is that WDL 1.0 is still very widely used and its spec deserves to be fixed for that reason.

I think the best way to do this would be to update the original in the case of clear typos and adding examples, but failing that, I lean towards annotating the original. At the very least there has to be a link on the original where someone can find the errata; if it's not linked in the current spec than it is unlikely people will find it.

**Comment by jdidion** [comment]
@notestaff @aofarrel if you'd still like to see this fixed in earlier versions of WDL (1.0 and earlier) please create a PR adding/updating an ERRATA doc adjacent to those versions of the spec. Thanks

**Pull request closed without merging**
