### PR TITLE
Add min, max to list of standard library methods

### PR DESCRIPTION
**Pull request by pshapiro4broad**
A spec addition for issue https://github.com/openwdl/wdl/issues/276

Also fix markdown typos in select_all, select_first

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Any reason to not also add this for `Float`?

**Comment by pshapiro4broad** [comment]
> Any reason to not also add this for Float?

No reason other than I didn't have any use cases in my code base. I can add it to the spec if you think it would be useful. Would you allow `Int` and `Float` in the same argument list and promote the result to `Float` (e.g. to match WDL's other binary numerical operations)?

I also thought about adding n-ary versions of `min` and `max` but again, didn't have any use cases on hand so I didn't bother adding it.

**Comment by cjllanwarne** [comment]
> Would you allow Int and Float in the same argument list and promote the result to Float (e.g. to match WDL's other binary numerical operations)?

=> Yes, I would do that, mainly to avoid annoying surprises

> I also thought about adding n-ary versions of min and max but again, didn't have any use cases on hand so I didn't bother adding it.

=> I agree

**Comment by DavyCats** [comment]
:+1:

**Comment by orodeh** [comment]
👍

**Comment by rhpvorderman** [comment]
:+1:

**Comment by illusional** [comment]
👍

**Comment by TMiguelT** [comment]
+1

**Comment by geoffjentry** [comment]
This passes and is now `waiting for implementation`

**Comment by cjllanwarne** [comment]
@pshapiro4broad this is now implemented (as of https://github.com/broadinstitute/cromwell/pull/5338) - could you resolve the conflicts on this PR and then I can go ahead and merge this into the spec. Thanks!

**Comment by rhpvorderman** [comment]
@pshapiro4broad, could you also add an entry to the new changelog?

**Comment by jdidion** [comment]
Now implemented in wdlTools

**Comment by jdidion** [comment]
This is in v1.1 and will be propagated to development.

**Pull request closed without merging**
