### PR TITLE
fix a few typos

### PR DESCRIPTION
**Pull request by azzaea**
Some of the illustrations to code snippet examples are not matched properly. These are a few suggested fixes (thanks @geoffjentry for pointing the `WDL development version`)

### CODE REVIEW

**Comment by geoffjentry** [comment]
Hi @azzaea - thanks for this. Despite the changes being typos, we'll still need to run this through the voting/review process. I'll point the community at this and if there are no concerns (it seems non-controversial to me) we'll run it through for a vote. Thanks!

**Comment by orodeh** [comment]
👍

**Comment by azzaea** [comment]
Fair enough. Happy to have contributed, and wish if done earlier.

**Comment by patmagee** [comment]
:+1:

**Comment by aednichols** [comment]
Love the attention to detail in this contrib but have to 👎 because it feels necessary to resolve this question (by deleting the line or removing the comment)
```
# This value is not needed actually, so better delete this line?
```

**Comment by azzaea** [comment]
Thank you @aednichols ! I intended to delete that line, but for some reason it felt right to justify myself here.
I haven't done this before, so if you don't mind me asking- when making the edit, do I create a new pull request; or it will be part of this one here?

**Comment by aednichols** [comment]
Since this PR is not yet being voted on, my understanding is that you can simply make the change here. The "no changes" rule applies when voting is active (presumably so that votes and changes are not interleaved, such that some people voted on one version and others voted on another). Hope this helps!

https://github.com/openwdl/wdl/blob/master/GOVERNANCE.md#rfc-process

**Comment by orodeh** [comment]
👍

**Comment by illusional** [comment]
👍

**Comment by DavyCats** [comment]
:+1:

**Comment by patmagee** [comment]
Passed with a vote of 3:0

**Pull request merged**
