### PR TITLE
[Hermes Grammar] Add none literal

### PR DESCRIPTION
**Pull request by cjllanwarne**
- Implementation detail for #263

### CODE REVIEW

**Comment by patmagee** [comment]
@cjllanwarne does this need to be voted on?

**Comment by cjllanwarne** [comment]
@patmagee I don't think so, although technical review is always welcome. 

It's just an implementation detail of #263

**Comment by patmagee** [comment]
to be honest I am not expert at hermes, and it LGTM? Maybe if @geoffjentry can weigh in or someone else just to make sure that everything looks good, then we can merge this

**Comment by geoffjentry** [comment]
Yeah, we don't vote on the hermes grammar changes as they're not part of the spec. will review

**Pull request merged**
