### PR TITLE
Proposal: remove object from the language - Revisit

### PR DESCRIPTION
**Pull request by patmagee**
@EvanTheB I have attempted to rebase your PR #228. In this PR I have also removed the offending example which causes issues in the other PR

@cjllanwarne  @geoffjentry can you please go over this with a fine toothed comb? The Rebase was quite ugly

### CODE REVIEW

**Comment by EvanTheB** [comment]
Apologies for the radio silence, lgtm

**Comment by cjllanwarne** [comment]
@patmagee this looks correct to me! Thanks again for doing that rebase!

Let me know if this needs a re-vote or whether it goes immediately to "waiting for implementation". If the latter then I can rebase and merge my PR in Cromwell and this should be mergeable right afterwards.

**Comment by cjllanwarne** [comment]
@patmagee just retesting this change in https://github.com/broadinstitute/cromwell/pull/4443 now, since it needed a rebase on some grammar changes which occurred in the meantime. After that happens, I'll be able to declare this one "implemented"

**Comment by cjllanwarne** [comment]
@patmagee implemented by broadinstitute/cromwell#4443 - so I think we can now:
- Close this PR as implemented
- Close grammar change #273 as a ride-along

**Pull request merged**
