### PR TITLE
Add `parameter_meta` to struct definition

### PR DESCRIPTION
**Pull request by jdidion**
### Checklist
- [x] Pull request details were added to CHANGELOG.md
- [x] Valid examples WDL's were added or updated to the SPEC.md (see the [guide](https://github.com/openwdl/wdl-tests/blob/main/docs/MarkdownTests.md) on writing markdown tests)

### CODE REVIEW

**Comment by vsmalladi** [comment]
@jdidion should this be merged to the 1.2 branch?

**Comment by jdidion** [comment]
@vsmalladi yes fixed now

**Review by illusional — COMMENTED** [review]
Is it an error if a parameter_meta contains extra fields?

**Comment by jdidion** [comment]
@illusional yes. In the task and workflow `parameter_meta` sections it says "This section contains metadata specific to input and output parameters. Any key in this section *must* correspond to a task input or output." So I think it's only consistent to put a similar requirement on `struct` `parameter_meta`.

**Review by patmagee — APPROVED** [review]
This looks god to me, Straight forward.

@jdidion For completeness do you think we should also allow a meta section? 

Also IIRC, meta and parameter_meta can both reference expressions (or maybe I am misremember). Are expressions allowed? Can they reference the values within

**Comment by jdidion** [comment]
@patmagee yes good point - no reason not to also allow `meta`.

Neither `meta` nor `parameter_meta` allow expressions. You might be thinking of `hints`, which we originally proposed would be like `meta` sections and not allow expressions, but have decided to instead make it like `requirements` and allow expressions.

**Review by patmagee — APPROVED** [review]
LGTM

**Pull request merged**
