### PR TITLE
Update version statement

### PR DESCRIPTION
**Pull request by ffinfo**
This makes it more compatible with header plugins.

### CODE REVIEW

**Comment by EvanTheB** [comment]
Neither statements nor comments are defined in this document.

**Comment by orodeh** [comment]
👍

**Comment by rhpvorderman** [comment]
:+1:

**Comment by cjllanwarne** [comment]
👍

**Comment by geoffjentry** [comment]
👍

**Comment by geoffjentry** [comment]
Votging passes and this is now waiting for implementation

**Pull request merged**
